version: '3'

services:
  db-postgres-calendar:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'db-postgres-calendar'
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  postgres-data:
